
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.hero
{
public sealed partial class HeroAttr : Luban.BeanBase
{
    public HeroAttr(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["heroID"].IsNumber) { throw new SerializationException(); }  HeroID = _buf["heroID"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { var __json0 = _buf["attrs"]; if(!__json0.IsArray) { throw new SerializationException(); } Attrs = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Attrs.Add(_k0, _v0); }   }
        { var __json0 = _buf["up"]; if(!__json0.IsArray) { throw new SerializationException(); } Up = new System.Collections.Generic.Dictionary<int, float>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } float _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Up.Add(_k0, _v0); }   }
        { if(!_buf["normalAtkID"].IsNumber) { throw new SerializationException(); }  NormalAtkID = _buf["normalAtkID"]; }
        { if(!_buf["battleSkill"].IsNumber) { throw new SerializationException(); }  BattleSkill = _buf["battleSkill"]; }
        { var __json0 = _buf["skillList"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillList.Add(__v0); }   }
        { var __json0 = _buf["beSkillList"]; if(!__json0.IsArray) { throw new SerializationException(); } BeSkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeSkillList.Add(__v0); }   }
        { var __json0 = _buf["bePvPSkillList"]; if(!__json0.IsArray) { throw new SerializationException(); } BePvPSkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BePvPSkillList.Add(__v0); }   }
        { if(!_buf["hpStarRate"].IsNumber) { throw new SerializationException(); }  HpStarRate = _buf["hpStarRate"]; }
        { if(!_buf["atkStarRate"].IsNumber) { throw new SerializationException(); }  AtkStarRate = _buf["atkStarRate"]; }
        { if(!_buf["jinjieshi"].IsNumber) { throw new SerializationException(); }  Jinjieshi = _buf["jinjieshi"]; }
        { var __json0 = _buf["needItems"]; if(!__json0.IsArray) { throw new SerializationException(); } NeedItems = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  NeedItems.Add(__v0); }   }
    }

    public static HeroAttr DeserializeHeroAttr(JSONNode _buf)
    {
        return new hero.HeroAttr(_buf);
    }

    public readonly int Id;
    public readonly int HeroID;
    public readonly int Star;
    /// <summary>
    /// 攻击\防御\生命\速度
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Attrs;
    /// <summary>
    /// 成长率
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, float> Up;
    public readonly int NormalAtkID;
    public readonly int BattleSkill;
    /// <summary>
    /// 主动技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> SkillList;
    /// <summary>
    /// 被动技能
    /// </summary>
    public readonly System.Collections.Generic.List<int> BeSkillList;
    public readonly System.Collections.Generic.List<int> BePvPSkillList;
    public readonly int HpStarRate;
    public readonly int AtkStarRate;
    public readonly int Jinjieshi;
    public readonly System.Collections.Generic.List<int> NeedItems;
   
    public const int __ID__ = -1422233441;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "heroID:" + HeroID + ","
        + "star:" + Star + ","
        + "attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "up:" + Luban.StringUtil.CollectionToString(Up) + ","
        + "normalAtkID:" + NormalAtkID + ","
        + "battleSkill:" + BattleSkill + ","
        + "skillList:" + Luban.StringUtil.CollectionToString(SkillList) + ","
        + "beSkillList:" + Luban.StringUtil.CollectionToString(BeSkillList) + ","
        + "bePvPSkillList:" + Luban.StringUtil.CollectionToString(BePvPSkillList) + ","
        + "hpStarRate:" + HpStarRate + ","
        + "atkStarRate:" + AtkStarRate + ","
        + "jinjieshi:" + Jinjieshi + ","
        + "needItems:" + Luban.StringUtil.CollectionToString(NeedItems) + ","
        + "}";
    }
}

}

