
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.hero
{
public partial class TbHeroAttr
{
    private readonly System.Collections.Generic.Dictionary<int, hero.HeroAttr> _dataMap;
    private readonly System.Collections.Generic.List<hero.HeroAttr> _dataList;
    
    public TbHeroAttr(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, hero.HeroAttr>();
        _dataList = new System.Collections.Generic.List<hero.HeroAttr>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            hero.HeroAttr _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = hero.HeroAttr.DeserializeHeroAttr(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, hero.HeroAttr> DataMap => _dataMap;
    public System.Collections.Generic.List<hero.HeroAttr> DataList => _dataList;

    public hero.HeroAttr GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public hero.HeroAttr Get(int key) => _dataMap[key];
    public hero.HeroAttr this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

