
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;

namespace cfg
{
public partial class Tables
{
    public hero.TbHero TbHero {get; }
    public hero.TbHeroAttr TbHeroAttr {get; }
    public hero.TbHeroExchange TbHeroExchange {get; }
    public gacha.TbGachaRate TbGachaRate {get; }
    public battle.TbBattleMap TbBattleMap {get; }
    public battle.TbBattleQuest TbBattleQuest {get; }
    public enemy.TbEnemy TbEnemy {get; }
    public enemy.TbEnemyGroup TbEnemyGroup {get; }
    public enemy.TbEnemyAttrs TbEnemyAttrs {get; }
    public skill.TbSkill TbSkill {get; }
    public item.TbItem TbItem {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbHero = new hero.TbHero(loader("hero_tbhero"));
        TbHeroAttr = new hero.TbHeroAttr(loader("hero_tbheroattr"));
        TbHeroExchange = new hero.TbHeroExchange(loader("hero_tbheroexchange"));
        TbGachaRate = new gacha.TbGachaRate(loader("gacha_tbgacharate"));
        TbBattleMap = new battle.TbBattleMap(loader("battle_tbbattlemap"));
        TbBattleQuest = new battle.TbBattleQuest(loader("battle_tbbattlequest"));
        TbEnemy = new enemy.TbEnemy(loader("enemy_tbenemy"));
        TbEnemyGroup = new enemy.TbEnemyGroup(loader("enemy_tbenemygroup"));
        TbEnemyAttrs = new enemy.TbEnemyAttrs(loader("enemy_tbenemyattrs"));
        TbSkill = new skill.TbSkill(loader("skill_tbskill"));
        TbItem = new item.TbItem(loader("item_tbitem"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbHero.ResolveRef(this);
        TbHeroAttr.ResolveRef(this);
        TbHeroExchange.ResolveRef(this);
        TbGachaRate.ResolveRef(this);
        TbBattleMap.ResolveRef(this);
        TbBattleQuest.ResolveRef(this);
        TbEnemy.ResolveRef(this);
        TbEnemyGroup.ResolveRef(this);
        TbEnemyAttrs.ResolveRef(this);
        TbSkill.ResolveRef(this);
        TbItem.ResolveRef(this);
    }
}

}
