
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public sealed partial class EnemyGroup : Luban.BeanBase
{
    public EnemyGroup(JSONNode _buf) 
    {
        { if(!_buf["enemyGroupID"].IsNumber) { throw new SerializationException(); }  EnemyGroupID = _buf["enemyGroupID"]; }
        { var __json0 = _buf["member"]; if(!__json0.IsArray) { throw new SerializationException(); } Member = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Member.Add(_k0, _v0); }   }
        { if(!_buf["formation"].IsNumber) { throw new SerializationException(); }  Formation = _buf["formation"]; }
        { var __json0 = _buf["beSkill"]; if(!__json0.IsArray) { throw new SerializationException(); } BeSkill = new System.Collections.Generic.List<int[]>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int[] __v0;  { var __json1 = __e0; if(!__json1.IsArray) { throw new SerializationException(); } int _n1 = __json1.Count; __v0 = new int[_n1]; int __index1=0; foreach(JSONNode __e1 in __json1.Children) { int __v1;  { if(!__e1.IsNumber) { throw new SerializationException(); }  __v1 = __e1; }  __v0[__index1++] = __v1; }   }  BeSkill.Add(__v0); }   }
        { if(!_buf["combatType"].IsNumber) { throw new SerializationException(); }  CombatType = _buf["combatType"]; }
        { var __json0 = _buf["attrID"]; if(!__json0.IsArray) { throw new SerializationException(); } AttrID = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  AttrID.Add(_k0, _v0); }   }
    }

    public static EnemyGroup DeserializeEnemyGroup(JSONNode _buf)
    {
        return new enemy.EnemyGroup(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int EnemyGroupID;
    /// <summary>
    /// 成员,等级
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Member;
    public readonly int Formation;
    public readonly System.Collections.Generic.List<int[]> BeSkill;
    public readonly int CombatType;
    public readonly System.Collections.Generic.Dictionary<int, int> AttrID;
   
    public const int __ID__ = -1965600227;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyGroupID:" + EnemyGroupID + ","
        + "member:" + Luban.StringUtil.CollectionToString(Member) + ","
        + "formation:" + Formation + ","
        + "beSkill:" + Luban.StringUtil.CollectionToString(BeSkill) + ","
        + "combatType:" + CombatType + ","
        + "attrID:" + Luban.StringUtil.CollectionToString(AttrID) + ","
        + "}";
    }
}

}

