
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public partial class TbEnemyAttrs
{
    private readonly System.Collections.Generic.Dictionary<int, enemy.EnemyAttrs> _dataMap;
    private readonly System.Collections.Generic.List<enemy.EnemyAttrs> _dataList;
    
    public TbEnemyAttrs(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, enemy.EnemyAttrs>();
        _dataList = new System.Collections.Generic.List<enemy.EnemyAttrs>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.EnemyAttrs _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = enemy.EnemyAttrs.DeserializeEnemyAttrs(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.AttrsID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, enemy.EnemyAttrs> DataMap => _dataMap;
    public System.Collections.Generic.List<enemy.EnemyAttrs> DataList => _dataList;

    public enemy.EnemyAttrs GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemy.EnemyAttrs Get(int key) => _dataMap[key];
    public enemy.EnemyAttrs this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

