
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.skill
{
public sealed partial class Skill : Luban.BeanBase
{
    public Skill(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["skillID"].IsNumber) { throw new SerializationException(); }  SkillID = _buf["skillID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsNumber) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["attackAction"].IsString) { throw new SerializationException(); }  AttackAction = _buf["attackAction"]; }
        { if(!_buf["attackEffect"].IsString) { throw new SerializationException(); }  AttackEffect = _buf["attackEffect"]; }
        { if(!_buf["flyEffect"].IsString) { throw new SerializationException(); }  FlyEffect = _buf["flyEffect"]; }
        { if(!_buf["hitEffect"].IsString) { throw new SerializationException(); }  HitEffect = _buf["hitEffect"]; }
        { if(!_buf["fireSound"].IsString) { throw new SerializationException(); }  FireSound = _buf["fireSound"]; }
        { if(!_buf["flySound"].IsString) { throw new SerializationException(); }  FlySound = _buf["flySound"]; }
        { if(!_buf["hitSound"].IsString) { throw new SerializationException(); }  HitSound = _buf["hitSound"]; }
    }

    public static Skill DeserializeSkill(JSONNode _buf)
    {
        return new skill.Skill(_buf);
    }

    public readonly int Id;
    public readonly int SkillID;
    public readonly string Name;
    public readonly int Icon;
    public readonly string Desc;
    public readonly string AttackAction;
    public readonly string AttackEffect;
    public readonly string FlyEffect;
    public readonly string HitEffect;
    public readonly string FireSound;
    public readonly string FlySound;
    public readonly string HitSound;
   
    public const int __ID__ = 1155715156;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "skillID:" + SkillID + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "desc:" + Desc + ","
        + "attackAction:" + AttackAction + ","
        + "attackEffect:" + AttackEffect + ","
        + "flyEffect:" + FlyEffect + ","
        + "hitEffect:" + HitEffect + ","
        + "fireSound:" + FireSound + ","
        + "flySound:" + FlySound + ","
        + "hitSound:" + HitSound + ","
        + "}";
    }
}

}

