
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.battle
{
public sealed partial class BattleQuest : Luban.BeanBase
{
    public BattleQuest(JSONNode _buf) 
    {
        { if(!_buf["QuestID"].IsNumber) { throw new SerializationException(); }  QuestID = _buf["QuestID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["mapID"].IsNumber) { throw new SerializationException(); }  MapID = _buf["mapID"]; }
        { if(!_buf["sceneID"].IsNumber) { throw new SerializationException(); }  SceneID = _buf["sceneID"]; }
        { if(!_buf["enemyGroupID"].IsNumber) { throw new SerializationException(); }  EnemyGroupID = _buf["enemyGroupID"]; }
        { if(!_buf["needLv"].IsNumber) { throw new SerializationException(); }  NeedLv = _buf["needLv"]; }
        { var __json0 = _buf["tongguan"]; if(!__json0.IsArray) { throw new SerializationException(); } Tongguan = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Tongguan.Add(_k0, _v0); }   }
        { var __json0 = _buf["winReward"]; if(!__json0.IsArray) { throw new SerializationException(); } WinReward = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  WinReward.Add(_k0, _v0); }   }
        { if(!_buf["dropID"].IsNumber) { throw new SerializationException(); }  DropID = _buf["dropID"]; }
    }

    public static BattleQuest DeserializeBattleQuest(JSONNode _buf)
    {
        return new battle.BattleQuest(_buf);
    }

    public readonly int QuestID;
    public readonly string Name;
    public readonly int MapID;
    public readonly int SceneID;
    public readonly int EnemyGroupID;
    public readonly int NeedLv;
    public readonly System.Collections.Generic.Dictionary<int, int> Tongguan;
    public readonly System.Collections.Generic.Dictionary<int, int> WinReward;
    public readonly int DropID;
   
    public const int __ID__ = -1193023820;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "QuestID:" + QuestID + ","
        + "name:" + Name + ","
        + "mapID:" + MapID + ","
        + "sceneID:" + SceneID + ","
        + "enemyGroupID:" + EnemyGroupID + ","
        + "needLv:" + NeedLv + ","
        + "tongguan:" + Luban.StringUtil.CollectionToString(Tongguan) + ","
        + "winReward:" + Luban.StringUtil.CollectionToString(WinReward) + ","
        + "dropID:" + DropID + ","
        + "}";
    }
}

}

