
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.battle
{
public partial class TbBattleMap
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BattleMap> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleMap> _dataList;
    
    public TbBattleMap(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BattleMap>();
        _dataList = new System.Collections.Generic.List<battle.BattleMap>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            battle.BattleMap _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = battle.BattleMap.DeserializeBattleMap(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.BattleMap> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.BattleMap> DataList => _dataList;

    public battle.BattleMap GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.BattleMap Get(int key) => _dataMap[key];
    public battle.BattleMap this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

