
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.battle
{
public partial class TbBattleQuest
{
    private readonly System.Collections.Generic.Dictionary<int, battle.BattleQuest> _dataMap;
    private readonly System.Collections.Generic.List<battle.BattleQuest> _dataList;
    
    public TbBattleQuest(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, battle.BattleQuest>();
        _dataList = new System.Collections.Generic.List<battle.BattleQuest>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            battle.BattleQuest _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = battle.BattleQuest.DeserializeBattleQuest(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.QuestID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, battle.BattleQuest> DataMap => _dataMap;
    public System.Collections.Generic.List<battle.BattleQuest> DataList => _dataList;

    public battle.BattleQuest GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public battle.BattleQuest Get(int key) => _dataMap[key];
    public battle.BattleQuest this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

