
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.hero
{
public sealed partial class Hero : Luban.BeanBase
{
    public Hero(JSONNode _buf) 
    {
        { if(!_buf["heroID"].IsNumber) { throw new SerializationException(); }  HeroID = _buf["heroID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["label"].IsString) { throw new SerializationException(); }  Label = _buf["label"]; }
        { if(!_buf["camp"].IsNumber) { throw new SerializationException(); }  Camp = _buf["camp"]; }
        { if(!_buf["hurtType"].IsNumber) { throw new SerializationException(); }  HurtType = _buf["hurtType"]; }
        { if(!_buf["job"].IsNumber) { throw new SerializationException(); }  Job = _buf["job"]; }
        { if(!_buf["sex"].IsNumber) { throw new SerializationException(); }  Sex = _buf["sex"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { if(!_buf["grade"].IsNumber) { throw new SerializationException(); }  Grade = _buf["grade"]; }
        { if(!_buf["isElite"].IsNumber) { throw new SerializationException(); }  IsElite = _buf["isElite"]; }
        { if(!_buf["isFuNeng"].IsNumber) { throw new SerializationException(); }  IsFuNeng = _buf["isFuNeng"]; }
        { if(!_buf["showDrawEffect"].IsNumber) { throw new SerializationException(); }  ShowDrawEffect = _buf["showDrawEffect"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
        { if(!_buf["width"].IsNumber) { throw new SerializationException(); }  Width = _buf["width"]; }
        { if(!_buf["head"].IsNumber) { throw new SerializationException(); }  Head = _buf["head"]; }
        { if(!_buf["body"].IsNumber) { throw new SerializationException(); }  Body = _buf["body"]; }
        { if(!_buf["quality"].IsNumber) { throw new SerializationException(); }  Quality = _buf["quality"]; }
        { if(!_buf["weightLv"].IsNumber) { throw new SerializationException(); }  WeightLv = _buf["weightLv"]; }
        { if(!_buf["seerLv"].IsNumber) { throw new SerializationException(); }  SeerLv = _buf["seerLv"]; }
        { if(!_buf["zhihuanLv"].IsNumber) { throw new SerializationException(); }  ZhihuanLv = _buf["zhihuanLv"]; }
        { if(!_buf["combatOffset"].IsNumber) { throw new SerializationException(); }  CombatOffset = _buf["combatOffset"]; }
        { if(!_buf["skin"].IsNumber) { throw new SerializationException(); }  Skin = _buf["skin"]; }
        { if(!_buf["gl"].IsNumber) { throw new SerializationException(); }  Gl = _buf["gl"]; }
        { if(!_buf["gm"].IsNumber) { throw new SerializationException(); }  Gm = _buf["gm"]; }
    }

    public static Hero DeserializeHero(JSONNode _buf)
    {
        return new hero.Hero(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int HeroID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    public readonly string Label;
    /// <summary>
    /// 阵营
    /// </summary>
    public readonly int Camp;
    /// <summary>
    /// 远程/近战
    /// </summary>
    public readonly int HurtType;
    /// <summary>
    /// 坦克/战士/法师
    /// </summary>
    public readonly int Job;
    public readonly int Sex;
    public readonly int Star;
    public readonly int Grade;
    public readonly int IsElite;
    public readonly int IsFuNeng;
    public readonly int ShowDrawEffect;
    public readonly int Height;
    public readonly int Width;
    public readonly int Head;
    public readonly int Body;
    public readonly int Quality;
    public readonly int WeightLv;
    public readonly int SeerLv;
    public readonly int ZhihuanLv;
    public readonly int CombatOffset;
    public readonly int Skin;
    public readonly int Gl;
    public readonly int Gm;
   
    public const int __ID__ = -2042717810;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "heroID:" + HeroID + ","
        + "name:" + Name + ","
        + "label:" + Label + ","
        + "camp:" + Camp + ","
        + "hurtType:" + HurtType + ","
        + "job:" + Job + ","
        + "sex:" + Sex + ","
        + "star:" + Star + ","
        + "grade:" + Grade + ","
        + "isElite:" + IsElite + ","
        + "isFuNeng:" + IsFuNeng + ","
        + "showDrawEffect:" + ShowDrawEffect + ","
        + "height:" + Height + ","
        + "width:" + Width + ","
        + "head:" + Head + ","
        + "body:" + Body + ","
        + "quality:" + Quality + ","
        + "weightLv:" + WeightLv + ","
        + "seerLv:" + SeerLv + ","
        + "zhihuanLv:" + ZhihuanLv + ","
        + "combatOffset:" + CombatOffset + ","
        + "skin:" + Skin + ","
        + "gl:" + Gl + ","
        + "gm:" + Gm + ","
        + "}";
    }
}

}

