
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.item
{
public sealed partial class Item : Luban.BeanBase
{
    public Item(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["itemType"].IsNumber) { throw new SerializationException(); }  ItemType = _buf["itemType"]; }
        { if(!_buf["isShow"].IsNumber) { throw new SerializationException(); }  IsShow = _buf["isShow"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["icon"].IsNumber) { throw new SerializationException(); }  Icon = _buf["icon"]; }
        { if(!_buf["order"].IsNumber) { throw new SerializationException(); }  Order = _buf["order"]; }
        { if(!_buf["effect"].IsNumber) { throw new SerializationException(); }  Effect = _buf["effect"]; }
        { if(!_buf["rare"].IsNumber) { throw new SerializationException(); }  Rare = _buf["rare"]; }
        { if(!_buf["desc1"].IsString) { throw new SerializationException(); }  Desc1 = _buf["desc1"]; }
        { if(!_buf["desc2"].IsString) { throw new SerializationException(); }  Desc2 = _buf["desc2"]; }
        { var __json0 = _buf["price"]; if(!__json0.IsArray) { throw new SerializationException(); } Price = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Price.Add(_k0, _v0); }   }
        { var __json0 = _buf["getway"]; if(!__json0.IsArray) { throw new SerializationException(); } Getway = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Getway.Add(__v0); }   }
    }

    public static Item DeserializeItem(JSONNode _buf)
    {
        return new item.Item(_buf);
    }

    public readonly int Id;
    public readonly int ItemType;
    public readonly int IsShow;
    public readonly string Name;
    public readonly int Icon;
    public readonly int Order;
    public readonly int Effect;
    public readonly int Rare;
    public readonly string Desc1;
    public readonly string Desc2;
    public readonly System.Collections.Generic.Dictionary<int, int> Price;
    public readonly System.Collections.Generic.List<int> Getway;
   
    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "itemType:" + ItemType + ","
        + "isShow:" + IsShow + ","
        + "name:" + Name + ","
        + "icon:" + Icon + ","
        + "order:" + Order + ","
        + "effect:" + Effect + ","
        + "rare:" + Rare + ","
        + "desc1:" + Desc1 + ","
        + "desc2:" + Desc2 + ","
        + "price:" + Luban.StringUtil.CollectionToString(Price) + ","
        + "getway:" + Luban.StringUtil.CollectionToString(Getway) + ","
        + "}";
    }
}

}

