
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public sealed partial class Enemy : Luban.BeanBase
{
    public Enemy(JSONNode _buf) 
    {
        { if(!_buf["enemyID"].IsNumber) { throw new SerializationException(); }  EnemyID = _buf["enemyID"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["camp"].IsNumber) { throw new SerializationException(); }  Camp = _buf["camp"]; }
        { if(!_buf["job"].IsNumber) { throw new SerializationException(); }  Job = _buf["job"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { if(!_buf["sex"].IsNumber) { throw new SerializationException(); }  Sex = _buf["sex"]; }
        { if(!_buf["height"].IsNumber) { throw new SerializationException(); }  Height = _buf["height"]; }
        { if(!_buf["width"].IsNumber) { throw new SerializationException(); }  Width = _buf["width"]; }
        { if(!_buf["head"].IsNumber) { throw new SerializationException(); }  Head = _buf["head"]; }
        { if(!_buf["body"].IsNumber) { throw new SerializationException(); }  Body = _buf["body"]; }
        { if(!_buf["normalAtkID"].IsNumber) { throw new SerializationException(); }  NormalAtkID = _buf["normalAtkID"]; }
        { var __json0 = _buf["skillList"]; if(!__json0.IsArray) { throw new SerializationException(); } SkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  SkillList.Add(__v0); }   }
        { var __json0 = _buf["beSkillList"]; if(!__json0.IsArray) { throw new SerializationException(); } BeSkillList = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  BeSkillList.Add(__v0); }   }
    }

    public static Enemy DeserializeEnemy(JSONNode _buf)
    {
        return new enemy.Enemy(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int EnemyID;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 阵营
    /// </summary>
    public readonly int Camp;
    /// <summary>
    /// 坦克/战士/法师
    /// </summary>
    public readonly int Job;
    public readonly int Star;
    public readonly int Sex;
    public readonly int Height;
    public readonly int Width;
    public readonly int Head;
    public readonly int Body;
    public readonly int NormalAtkID;
    public readonly System.Collections.Generic.List<int> SkillList;
    public readonly System.Collections.Generic.List<int> BeSkillList;
   
    public const int __ID__ = -1023814270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enemyID:" + EnemyID + ","
        + "name:" + Name + ","
        + "camp:" + Camp + ","
        + "job:" + Job + ","
        + "star:" + Star + ","
        + "sex:" + Sex + ","
        + "height:" + Height + ","
        + "width:" + Width + ","
        + "head:" + Head + ","
        + "body:" + Body + ","
        + "normalAtkID:" + NormalAtkID + ","
        + "skillList:" + Luban.StringUtil.CollectionToString(SkillList) + ","
        + "beSkillList:" + Luban.StringUtil.CollectionToString(BeSkillList) + ","
        + "}";
    }
}

}

