
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public sealed partial class EnemyAttrs : Luban.BeanBase
{
    public EnemyAttrs(JSONNode _buf) 
    {
        { if(!_buf["attrsID"].IsNumber) { throw new SerializationException(); }  AttrsID = _buf["attrsID"]; }
        { var __json0 = _buf["attrs"]; if(!__json0.IsArray) { throw new SerializationException(); } Attrs = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Attrs.Add(_k0, _v0); }   }
    }

    public static EnemyAttrs DeserializeEnemyAttrs(JSONNode _buf)
    {
        return new enemy.EnemyAttrs(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int AttrsID;
    /// <summary>
    /// 攻击\防御\生命\速度
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Attrs;
   
    public const int __ID__ = -1971077056;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "attrsID:" + AttrsID + ","
        + "attrs:" + Luban.StringUtil.CollectionToString(Attrs) + ","
        + "}";
    }
}

}

