
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.enemy
{
public partial class TbEnemyGroup
{
    private readonly System.Collections.Generic.Dictionary<int, enemy.EnemyGroup> _dataMap;
    private readonly System.Collections.Generic.List<enemy.EnemyGroup> _dataList;
    
    public TbEnemyGroup(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, enemy.EnemyGroup>();
        _dataList = new System.Collections.Generic.List<enemy.EnemyGroup>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            enemy.EnemyGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = enemy.EnemyGroup.DeserializeEnemyGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.EnemyGroupID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, enemy.EnemyGroup> DataMap => _dataMap;
    public System.Collections.Generic.List<enemy.EnemyGroup> DataList => _dataList;

    public enemy.EnemyGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public enemy.EnemyGroup Get(int key) => _dataMap[key];
    public enemy.EnemyGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

