
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.hero
{
public sealed partial class HeroExchange : Luban.BeanBase
{
    public HeroExchange(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["star"].IsNumber) { throw new SerializationException(); }  Star = _buf["star"]; }
        { var __json0 = _buf["item"]; if(!__json0.IsArray) { throw new SerializationException(); } Item = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Item.Add(_k0, _v0); }   }
    }

    public static HeroExchange DeserializeHeroExchange(JSONNode _buf)
    {
        return new hero.HeroExchange(_buf);
    }

    public readonly int Id;
    public readonly int Star;
    public readonly System.Collections.Generic.Dictionary<int, int> Item;
   
    public const int __ID__ = 117382609;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "star:" + Star + ","
        + "item:" + Luban.StringUtil.CollectionToString(Item) + ","
        + "}";
    }
}

}

