
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.hero
{
public partial class TbHero
{
    private readonly System.Collections.Generic.Dictionary<int, hero.Hero> _dataMap;
    private readonly System.Collections.Generic.List<hero.Hero> _dataList;
    
    public TbHero(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, hero.Hero>();
        _dataList = new System.Collections.Generic.List<hero.Hero>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            hero.Hero _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = hero.Hero.DeserializeHero(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.HeroID, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, hero.Hero> DataMap => _dataMap;
    public System.Collections.Generic.List<hero.Hero> DataList => _dataList;

    public hero.Hero GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public hero.Hero Get(int key) => _dataMap[key];
    public hero.Hero this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

