
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.gacha
{
public sealed partial class GachaRate : Luban.BeanBase
{
    public GachaRate(JSONNode _buf) 
    {
        { if(!_buf["gachaId"].IsNumber) { throw new SerializationException(); }  GachaId = _buf["gachaId"]; }
        { var __json0 = _buf["rate"]; if(!__json0.IsArray) { throw new SerializationException(); } Rate = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Rate.Add(_k0, _v0); }   }
    }

    public static GachaRate DeserializeGachaRate(JSONNode _buf)
    {
        return new gacha.GachaRate(_buf);
    }

    /// <summary>
    /// ID
    /// </summary>
    public readonly int GachaId;
    /// <summary>
    /// 概率
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Rate;
   
    public const int __ID__ = 273499126;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "gachaId:" + GachaId + ","
        + "rate:" + Luban.StringUtil.CollectionToString(Rate) + ","
        + "}";
    }
}

}

