
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.gacha
{
public partial class TbGachaRate
{
    private readonly System.Collections.Generic.Dictionary<int, gacha.GachaRate> _dataMap;
    private readonly System.Collections.Generic.List<gacha.GachaRate> _dataList;
    
    public TbGachaRate(JSONNode _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, gacha.GachaRate>();
        _dataList = new System.Collections.Generic.List<gacha.GachaRate>();
        
        foreach(JSONNode _ele in _buf.Children)
        {
            gacha.GachaRate _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = gacha.GachaRate.DeserializeGachaRate(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.GachaId, _v);
        }
    }

    public System.Collections.Generic.Dictionary<int, gacha.GachaRate> DataMap => _dataMap;
    public System.Collections.Generic.List<gacha.GachaRate> DataList => _dataList;

    public gacha.GachaRate GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public gacha.GachaRate Get(int key) => _dataMap[key];
    public gacha.GachaRate this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

