
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using SimpleJSON;


namespace cfg.battle
{
public sealed partial class BattleMap : Luban.BeanBase
{
    public BattleMap(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["bg"].IsNumber) { throw new SerializationException(); }  Bg = _buf["bg"]; }
        { if(!_buf["diff"].IsNumber) { throw new SerializationException(); }  Diff = _buf["diff"]; }
        { var __json0 = _buf["dropItemsShow"]; if(!__json0.IsArray) { throw new SerializationException(); } DropItemsShow = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  DropItemsShow.Add(_k0, _v0); }   }
        { if(!_buf["pos"].IsObject) { throw new SerializationException(); }  Pos = vector2.Deserializevector2(_buf["pos"]);  }
        { if(!_buf["build"].IsNumber) { throw new SerializationException(); }  Build = _buf["build"]; }
        { if(!_buf["des"].IsString) { throw new SerializationException(); }  Des = _buf["des"]; }
        { var __json0 = _buf["reward"]; if(!__json0.IsArray) { throw new SerializationException(); } Reward = new System.Collections.Generic.Dictionary<int, int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int _k0;  { if(!__e0[0].IsNumber) { throw new SerializationException(); }  _k0 = __e0[0]; } int _v0;  { if(!__e0[1].IsNumber) { throw new SerializationException(); }  _v0 = __e0[1]; }  Reward.Add(_k0, _v0); }   }
    }

    public static BattleMap DeserializeBattleMap(JSONNode _buf)
    {
        return new battle.BattleMap(_buf);
    }

    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 背景
    /// </summary>
    public readonly int Bg;
    /// <summary>
    /// 难度
    /// </summary>
    public readonly int Diff;
    /// <summary>
    /// 获得道具
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> DropItemsShow;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly vector2 Pos;
    /// <summary>
    /// 建筑
    /// </summary>
    public readonly int Build;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Des;
    /// <summary>
    /// 奖励
    /// </summary>
    public readonly System.Collections.Generic.Dictionary<int, int> Reward;
   
    public const int __ID__ = 244563886;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "bg:" + Bg + ","
        + "diff:" + Diff + ","
        + "dropItemsShow:" + Luban.StringUtil.CollectionToString(DropItemsShow) + ","
        + "pos:" + Pos + ","
        + "build:" + Build + ","
        + "des:" + Des + ","
        + "reward:" + Luban.StringUtil.CollectionToString(Reward) + ","
        + "}";
    }
}

}

